### ISSUE TITLE
undefined method `rindex' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by AntonBakaev** [civisanalytics/swagger-diff#40]
Hello,
I have a problem with comparing two schemes:
**undefined method `rindex' for nil:NilClass (NoMethodError)**

I'm attaching two schemes and error text.
[files.zip](https://github.com/civisanalytics/swagger-diff/files/553214/files.zip)

**Comment by jeffreyc** [comment]
Thank you for your feedback! From your stack trace, it looks like you're using Swagger::Diff 1.0.2. Swagger::Diff is up to 1.1.0, and several bugs have been fixed since 1.0.2. I don't have any issues comparing the attached specifications using 1.1.0, so upgrading should resolve your issue.

I'm going to close this issue, but please comment on this issue or file another issue as appropriate if you encounter any other problems with Swagger::Diff.

**Comment by AntonBakaev** [comment]
Thank you for help, now I have no problems with swagger-diff.
