### ISSUE TITLE
In the diff result path parameters are not populated

### ISSUE THREAD

**Issue by shwetap051** [civisanalytics/swagger-diff#41]
When using swagger-diff in the result the path parameter is not populated and empty curly braces shows up, is this a known issue?

e.g. like below /v6.0/test/{}/test/{}

**Comment by jeffreyc** [comment]
Thank you for your feedback! This is the expected behavior for Swagger::Diff. Changing the name of a path parameter (e.g., `/foo/{id}` vs `/foo/{foo_id}`) is not a breaking change as far as a client is concerned, so Swagger:Diff abstracts them to `{}`. This allows you to rename path parameters for consistency and convenience without Swagger::Diff flagging them as breaking changes.

I'm going to close this issue, but please comment on this issue or file another issue as appropriate if you encounter any other problems with Swagger::Diff.
