### ISSUE TITLE
New required form parameter is not a breaking change?

### ISSUE THREAD

**Issue by davidvc** [civisanalytics/swagger-diff#6]
Hi.  I am loving swagger-diff.  But I noticed that if I add a new required form-based param, this does not cause swagger-diff to report a diff.  If I change this to a query-param it does report a diff.

Is that correct?  It seems like a new required form param would break clients...

Thanks!

David

**Comment by jeffreyc** [comment]
This is most definitely not correct. Adding required parameters should be treated as a breaking change *unless* they are new body parameters contained in a new optional schema.

It looks like there's a bug parsing header and formData parameters, so not only did it miss the required parameters, it missed the parameters altogether. This will be fixed in #8.

Thank you for your report! It's great to hear that you're using (and loving) swagger-diff :)
